# https://github.com/JanMalch/argus

directory = ".argus" # default

[ui]
# Vertical layout: exchange view underneath timeline
horizontal = false
# Flexbox layout: exchange view is 1.5 times larger than the timeline
grow_timeline = 2
grow_exchange = 3
# casing and space/underscore doesn't matter. Unknown values are ignored.
timeline_columns = ["ID", "start", "method", "host", "request target", "end", "duration", "status_code", "status_Text"]

[[server]]
upstream = "https://jsonplaceholder.typicode.com"
port = 3000 # for localhost

[server.response.overwrites]
# Any request to "/comments/1" will immediately receive the file's content as a response.
# The file must be inside the directory specified above.
"/comments/1" = "any_method_1_response.json"
# You may also precisely select the HTTP method to overwrite.
"GET /comments/6" = "custom_get_6_response.json"
"POST /comments/6" = "custom_post_6_response.json"
# When the request target starts with a ^, it's intepreted as a GoLang regex.
# Otherwise it's used as an exact match.
"^/images/.+" = "img/16_9.png" # see the images directory, for some helpful images
# When using an integer value, Argus will immediately respond with no body and the given status code.
"GET ^/todos/\\d+" = 403

# You can specify as many servers as you like, but you cannot add them at runtime.
[[server]]
upstream = "https://postman-echo.com" # The upstream can be changed at runtime.
# you can specify the port explicitly, otherwise it's +1 to previous server

[server.request.headers]
# Overwite any existing headers. This allows you to quickly switch been stages without any restarts.
"X-API-Key" = "Hi"
# An empty string will remove the header
"X-Drop" = ""

[server.request.parameters]
# Add any query parameter, e.g. for cache busting
"__cache_buster" = "{{rng.uuid}}"

[server.response.headers]
# Add response headers to ease debugging with your application
"X-Argus-ID" = "{{id}}"
